#ifndef	IMPR_VERSION_INCLUDED
#define IMPR_VERSION_INCLUDED

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#define IMPR_VERSION_MAJOR	1
#define IMPR_VERSION_MINOR	0
#define IMPR_VERSION_PATCH	1
#define IMPR_VERSION_BETA	0
#define IMPR_VERSION_VERSTRING	MAKE_STR(IMPR_VERSION_MAJOR) "." MAKE_STR(IMPR_VERSION_MINOR) "." MAKE_STR(IMPR_VERSION_PATCH) "." MAKE_STR(IMPR_VERSION_BETA)

#endif
